source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '2.5.3'

gem 'agoo' # fast server
gem 'roda'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_import_export'
gem 'opal-autoloader', '~> 0.0.3'
gem 'opal-webpack-loader', '~> 0.3.7'
#gem 'isomorfeus-redux', '~> 4.0.0'
#gem 'isomorfeus-react', '~> 16.6.1'
gem 'isomorfeus-redux', path: '/Users/jan/workspace/isomorfeus-redux/ruby'
gem 'isomorfeus-react', path: '/Users/jan/workspace/isomorfeus-react/ruby'