source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem 'iodine', '~> 0.7.33'
gem 'foreman', require: false

gem 'roda', '~> 3.22.0'

gem 'opal', github: 'janbiedermann/opal', branch: 'es6_modules_1_1'
gem 'opal-activesupport', '~> 0.3.3'
gem 'opal-webpack-loader', '>= 0.9.2'

gem 'isomorfeus-redux', '~> 4.0.11'
gem 'isomorfeus-react', '>= 16.9.2'
gem 'isomorfeus-transport', path: '../../isomorfeus-transport'
gem 'isomorfeus-data', path: '../../isomorfeus-data'
gem 'isomorfeus-i18n', path: '..'

group :development do
  gem 'auto_reloader'
  gem 'debase', '0.3.0.beta3'
  gem 'ruby-debug-ide', '0.8.0.beta3'
end

group :test do
  gem 'rspec', '~> 3.8.0'
  gem 'isomorfeus-puppetmaster', '~> 0.2.9'
end
